# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_code', models.CharField(max_length=3)),
                ('destination_code', models.CharField(max_length=3)),
                ('destination_name', models.CharField(max_length=35)),
                ('one_way', models.BooleanField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('price', models.IntegerField()),
                ('stops', models.IntegerField()),
                ('trip_class', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('to_expose', models.BooleanField()),
                ('found_at', models.DateTimeField()),
                ('snapshot', models.CharField(max_length=50)),
            ],
        ),
    ]
