# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=50)),
                ('rus_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('eng_address', models.TextField()),
                ('rus_address', models.TextField()),
                ('b_number', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('country_id', models.IntegerField()),
                ('UFI', models.IntegerField()),
                ('types', models.CharField(max_length=100)),
                ('google_place_id', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('fpid', models.IntegerField()),
                ('dup', models.IntegerField()),
                ('chd_airports', models.TextField()),
                ('city_code', models.CharField(max_length=3)),
            ],
        ),
    ]
