# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0002_gplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('eng_name', models.CharField(max_length=50)),
                ('direction_id', models.IntegerField()),
                ('rus_name', models.CharField(max_length=50)),
                ('kdb_id', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='GDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=50)),
                ('rus_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
