# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0003_gcountry_gdirection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcountry',
            name='direction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enot_app.GDirection'),
        ),
        migrations.AlterField(
            model_name='gplace',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enot_app.GCountry'),
        ),
    ]
