# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0004_auto_20170219_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gcountry',
            old_name='direction_id',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='gplace',
            old_name='country_id',
            new_name='country',
        ),
    ]
