# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0005_auto_20170219_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
                ('tmp_country', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('total_bid_count', models.IntegerField()),
                ('average_price', models.IntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enot_app.GPlace')),
            ],
        ),
    ]
