# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0007_auto_20170223_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='TpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('requested_at', models.DateTimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpr_destination', to='enot_app.Destination')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpr_origin', to='enot_app.Destination')),
            ],
        ),
    ]
