# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0008_tprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tprequest',
            name='requested_at',
            field=models.DateTimeField(default=datetime.datetime(1979, 6, 30, 9, 30)),
        ),
    ]
