# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0010_auto_20170304_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tprequest',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='tprequest',
            name='origin',
        ),
        migrations.DeleteModel(
            name='TpRequest',
        ),
    ]
