# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0012_tpask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpask',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='tpask',
            name='origin',
        ),
        migrations.DeleteModel(
            name='TpAsk',
        ),
    ]
