# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0016_destination_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderquerytp',
            name='start_date',
            field=models.DateField(),
        ),
    ]
