# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0017_auto_20170304_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderquerytp',
            name='expires_at',
            field=models.DateField(),
        ),
    ]
