# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0018_auto_20170304_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='snapshot',
            new_name='signature',
        ),
    ]
