# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0019_auto_20170304_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='signature',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
