# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0020_auto_20170305_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderquerytp',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
