# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0021_spiderquerytp_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('confirmed', models.BooleanField(default=False)),
                ('last_mail_sent_at', models.DateTimeField()),
                ('premium', models.BooleanField(default=False)),
                ('interval', models.IntegerField(default=1)),
            ],
        ),
    ]
