# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0023_auto_20170308_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='tester',
            field=models.BooleanField(default=False),
        ),
    ]
