# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0025_auto_20170310_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='hsh',
            field=models.CharField(default='', max_length=50),
        ),
    ]
