# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0026_subscriber_hsh'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='pre_rating',
            field=models.IntegerField(default=0),
        ),
    ]
