# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0028_bid_chd_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
