# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0029_airline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('carriers', models.CharField(max_length=25)),
                ('slices', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('rt_comfort', models.IntegerField(default=0)),
                ('rt_price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
