# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0030_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination_code',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_code',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
