# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0031_auto_20170318_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='return_code',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
