# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0032_trip_return_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='invite_code',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(default='K', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='hsh',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='invite',
            name='emitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enot_app.Subscriber'),
        ),
    ]
