# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0033_auto_20170318_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='emitter',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
