# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0034_auto_20170318_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('interval', models.IntegerField(default=1)),
                ('confirmed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('premium', models.BooleanField(default=False)),
                ('tester', models.BooleanField(default=False)),
                ('last_mail_sent_at', models.DateTimeField()),
                ('invite_code', models.CharField(max_length=50)),
                ('hsh', models.CharField(max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='invite',
            name='emitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enot_app.Subscriber'),
        ),
    ]
