# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0035_auto_20170318_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='released_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='hsh',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='last_mail_sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
