# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0036_auto_20170318_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(auto_now_add=True, unique=True)),
                ('qpx_requests', models.IntegerField(default=0)),
            ],
        ),
    ]
