# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0040_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='chd_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pre_rating',
            field=models.IntegerField(null=True),
        ),
    ]
