# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0041_auto_20170319_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='benefits',
            field=models.TextField(null=True),
        ),
    ]
