# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0042_auto_20170319_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='penalties',
            field=models.TextField(null=True),
        ),
    ]
