# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0043_trip_penalties'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='planner_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stat',
            name='planner_started',
            field=models.BooleanField(default=False),
        ),
    ]
