# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0044_auto_20170321_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stat',
            new_name='Status',
        ),
    ]
