# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0047_remove_trip_rt_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='rt_price',
            field=models.IntegerField(default=0),
        ),
    ]
