# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0049_status_forced'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='bid_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enot_app.Destination'),
        ),
    ]
