# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0051_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='average_price',
            field=models.IntegerField(null=True),
        ),
    ]
