# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0052_trip_average_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
