# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0053_destination_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='score',
        ),
    ]
