# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0054_remove_destination_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='top_comfort',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='top_price',
            field=models.BooleanField(default=False),
        ),
    ]
