# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0056_auto_20170411_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='expose',
            field=models.BooleanField(default=False),
        ),
    ]
