# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-12 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0057_trip_expose'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='actual',
            field=models.BooleanField(default=True),
        ),
    ]
