# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0058_trip_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tmp_eff',
            field=models.IntegerField(default=0),
        ),
    ]
