# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0060_auto_20170419_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='carriers_names',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='days_text',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
