# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0061_auto_20170419_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='days_to',
            field=models.IntegerField(null=True),
        ),
    ]
