# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0063_auto_20170419_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrier',
            new_name='Airline',
        ),
    ]
