# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0064_auto_20170419_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
    ]
