# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0065_carrier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airline',
        ),
    ]
