# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-22 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0066_delete_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='days_to_text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
