# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0067_auto_20170422_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='build',
            field=models.TextField(null=True),
        ),
    ]
