# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0070_subscriber_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='last_issue',
            new_name='last_issue_number',
        ),
    ]
