# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0074_auto_20170425_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='stop_list',
            field=models.TextField(null=True),
        ),
    ]
