# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0075_issue_stop_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='origin_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enot_app.City'),
        ),
    ]
