# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0076_trip_origin_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
