# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0079_auto_20170505_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='hsh',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
