# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-15 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0080_auto_20170515_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='hsh',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
