# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-24 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0081_auto_20170515_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route_points',
            field=models.TextField(null=True),
        ),
    ]
