# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-24 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0083_remove_subscriber_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='hsh',
        ),
    ]
