# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-24 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0084_remove_subscriber_hsh'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='email',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='hsh',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
