# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0086_bid_best_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='api_request_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
