# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0087_status_api_request_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enot_app.GPlace'),
        ),
    ]
