# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0088_airport_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='carriers',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='carriers_names',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='days_text',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='days_to',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='days_to_text',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='penalties',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='route_points',
        ),
        migrations.AddField(
            model_name='trip',
            name='hd',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
