# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-04 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0090_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='place',
        ),
        migrations.DeleteModel(
            name='Tip',
        ),
    ]
