# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-04 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0091_auto_20170604_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('chd_data', models.TextField()),
                ('chd_rating', models.IntegerField(default=0)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enot_app.GPlace')),
            ],
        ),
    ]
