# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0094_auto_20170604_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('segment', models.CharField(choices=[('low', 'LOW'), ('mid', 'MID'), ('high', 'HIGH')], default='mid', max_length=5)),
                ('blink', models.CharField(max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enot_app.GPlace')),
            ],
        ),
    ]
