# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0095_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('see', models.IntegerField(default=0)),
                ('bch', models.IntegerField(default=0)),
                ('fod', models.IntegerField(default=0)),
                ('ski', models.IntegerField(default=0)),
                ('nlf', models.IntegerField(default=0)),
                ('hst', models.IntegerField(default=0)),
                ('dve', models.IntegerField(default=0)),
                ('shp', models.IntegerField(default=0)),
                ('kid', models.IntegerField(default=0)),
                ('bea', models.IntegerField(default=0)),
                ('mnt', models.IntegerField(default=0)),
                ('isl', models.IntegerField(default=0)),
                ('mar', models.IntegerField(default=0)),
                ('novisa', models.IntegerField(default=0)),
                ('nopass', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='gplace',
            name='keys',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='enot_app.PlaceKeys'),
        ),
    ]
