# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0095_hotel'),
        ('enot_app', '0080_auto_20170515_2011'),
    ]

    operations = [
    ]
