# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0096_auto_20170607_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gplace',
            name='keys',
        ),
        migrations.AddField(
            model_name='gplace',
            name='bch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gplace',
            name='bea',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gplace',
            name='dve',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gplace',
            name='fod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gplace',
            name='hst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gplace',
            name='isl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gplace',
            name='kid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gplace',
            name='mar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gplace',
            name='mnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gplace',
            name='nlf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gplace',
            name='see',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gplace',
            name='shp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gplace',
            name='ski',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PlaceKeys',
        ),
    ]
