# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0097_auto_20170607_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gplace',
            old_name='bch',
            new_name='key_bch',
        ),
        migrations.RenameField(
            model_name='gplace',
            old_name='bea',
            new_name='key_bea',
        ),
        migrations.RenameField(
            model_name='gplace',
            old_name='dve',
            new_name='key_dve',
        ),
        migrations.RenameField(
            model_name='gplace',
            old_name='fod',
            new_name='key_fod',
        ),
        migrations.RenameField(
            model_name='gplace',
            old_name='hst',
            new_name='key_hst',
        ),
        migrations.RenameField(
            model_name='gplace',
            old_name='isl',
            new_name='key_isl',
        ),
        migrations.RenameField(
            model_name='gplace',
            old_name='kid',
            new_name='key_kid',
        ),
        migrations.RenameField(
            model_name='gplace',
            old_name='mar',
            new_name='key_mar',
        ),
        migrations.RenameField(
            model_name='gplace',
            old_name='mnt',
            new_name='key_mnt',
        ),
        migrations.RenameField(
            model_name='gplace',
            old_name='nlf',
            new_name='key_nlf',
        ),
        migrations.RenameField(
            model_name='gplace',
            old_name='see',
            new_name='key_see',
        ),
        migrations.RenameField(
            model_name='gplace',
            old_name='shp',
            new_name='key_shp',
        ),
        migrations.RenameField(
            model_name='gplace',
            old_name='ski',
            new_name='key_ski',
        ),
    ]
