# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0099_quote_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tags',
        ),
    ]
