# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-08 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0102_auto_20170607_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tplink',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
