# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-08 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0103_trip_tplink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='tplink',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
