# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-11 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0104_auto_20170608_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
