# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0104_auto_20170608_0724'),
        ('enot_app', '0096_merge_20170607_0903'),
    ]

    operations = [
    ]
