# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0105_card_published'),
        ('enot_app', '0105_merge_20170608_1355'),
    ]

    operations = [
    ]
