# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0106_trip_direct'),
        ('enot_app', '0106_merge_20170611_1250'),
    ]

    operations = [
    ]
