# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-23 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0106_trip_direct'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
