# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enot_app', '0107_trip_new'),
        ('enot_app', '0107_merge_20170622_2012'),
    ]

    operations = [
    ]
